name: Deploy CV
on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Setup Typst
      uses: typst-community/setup-typst@v4
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install minify
      run: npm install -g minify
    - name: Create the build directory
      run: |
        mkdir build
    - name: Build Typst files
      run: |
        typst compile --root . typst/cv.typ --font-path static/fonts/ build/aplatonov-cv.pdf
    - name: Build web page
      run: |
        uv run scripts/render.py web/index.html.j2 data.yaml - > build/index.html
        minify -i build/index.html
        minify web/styles.css > build/styles.css
        cp static/avatar.jpeg build/
        uv run scripts/generate_favicons.py static/avatar.jpeg --output-dir build
    - name: Add custom CNAME
      run: echo cv.platonoff.dev > ./build/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./build
